### ISSUE TITLE
Unable to install myjson

### ISSUE THREAD

**Issue by toddpratt** [roundar/myjson#1]
$ pip install myjson
Collecting myjson
  Using cached https://files.pythonhosted.org/packages/7e/56/4c1e1be1cbffababd4fccbee8abe2656b1cb645d23542150bb6e252a2905/myjson-1.1.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n8dq25_b/myjson/setup.py", line 9, in <module>
        long_description=open(os.path.join(os.path.dirname(__file__), "readme.rst")).read(),
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-n8dq25_b/myjson/readme.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-n8dq25_b/myjson/

I'm at latest version of pip:
(.venv) tpratt@yorm:~/vision$ pip install --upgrade pip
Requirement already up-to-date: pip in ./.venv/lib/python3.6/site-packages (18.1)

This is on python 3.6.7 inside a virtualenv.

I can install other python modules.

I came across this when researching how to fix this: https://github.com/dopefishh/pympi/issues/5

**Comment by Ronkiro** [comment]
I think it's supposed to work only for python 2.

**Comment by toddpratt** [comment]
The code itself is python3 compatible (the try around the imports).  I tested it on my python and it worked correctly.  I suppose it's just a change to how the package is produced for py3.  I've never published a module so I don't know how that works.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by roundar** [comment]
At the very least I can prevent that error when the readme isn’t found until I know why it isn’t found. It may be a day or two though before I have an opportunity.

Rob

**Comment by Figgs** [comment]
Hello!
I'm also facing the same issue.

I believe the issue it's because somehow the installer is adding an extra / to the path

 IOError: [Errno 2] No such file or directory: 'c:\\users\\userID\\appdata\\local\\temp\\pip-install-emwiah\\myjson\\readme.rst'

Thanks in advance for your help!

**Comment by GWAndrew** [comment]
I found a fix to this error. (I'm using Python 3.6.8 and Windows 10 64bit)

First you have to download the .zip here : https://pypi.org/project/myjson/1.1.1/#files
Then extract it.

After you need to open that folder, you will see a file called ''setup.py'', open it when an code editor and delete this line "long_description=open(os.path.join(os.path.dirname(__file__), "readme.rst")).read(),".

Then save it.

Now, open the cmd at the folder's directory and write : "python ./setup.py install"

That's it ! You just installed myjson.

I hope it will work for you and thanks for reading, have a nice day !
